name: Pre-Release
on:
  release:
    types:
      - prereleased
jobs:
  dryRun:
    name: Dry Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --dry-run